"""Train the baseline CNN models."""

from datetime import datetime
from pathlib import Path
import random

import numpy as np
import pandas as pd
import torch

from src.data import load_split_tensors
from src.models import build_baseline_model
from src.training import (
    LR_RUN,
    EPOCHS_RUN,
    PATIENCE_RUN,
    STOP_METRIC,
    create_criterion,
    create_optimizer,
    create_scheduler,
    create_amp,
    epoch_baseline,
)


# Reproducibility
SEED = 42

random.seed(SEED)
np.random.seed(SEED)
torch.manual_seed(SEED)
torch.cuda.manual_seed_all(SEED)

torch.backends.cudnn.benchmark = True
torch.backends.cuda.matmul.allow_tf32 = True
torch.set_float32_matmul_precision("high")


# Device
device = torch.device(
    "cuda" if torch.cuda.is_available() else "cpu"
)

print(
    "Device:",
    device,
    "|",
    torch.cuda.get_device_name(0)
    if device.type == "cuda"
    else "CPU",
)

assert device.type == "cuda", (
    "CUDA not available. Install CUDA PyTorch and try again."
)


# Validation split generated by the refactored pipeline
SPLIT_DIR = Path(
    "_validation_runs/CVD_split"
)

NUM_CLASSES = 2
BATCH_SIZE = 32


# Input normalization
MEAN = torch.tensor(
    [0.5, 0.5, 0.5],
    dtype=torch.float32,
    device=device,
)

STD = torch.tensor(
    [0.25, 0.25, 0.25],
    dtype=torch.float32,
    device=device,
)


# Baseline experiments
MODELS = {
    "densenet121": {
        "output_dir": Path(
            "_validation_runs/results/densenet121"
        ),
        "checkpoint": Path(
            "_validation_runs/checkpoints/densenet121_best.pth"
        ),
    },

    "efficientnet_b3": {
        "output_dir": Path(
            "_validation_runs/results/efficientnet_b3"
        ),
        "checkpoint": Path(
            "_validation_runs/checkpoints/efficientnet_b3_best.pth"
        ),
    },

    "mobilenetv3_large": {
        "output_dir": Path(
            "_validation_runs/results/mobilenetv3_large"
        ),
        "checkpoint": Path(
            "_validation_runs/checkpoints/mobilenetv3_large_best.pth"
        ),
    },
}


# Load train, validation, and test tensors
(
    Xtr,
    Ytr,
    Xva,
    Yva,
    Xte,
    Yte,
    tr_names,
    va_names,
    te_names,
) = load_split_tensors(
    split_dir=SPLIT_DIR,
    device=device,
    mean=MEAN,
    std=STD,
)


# Train each baseline model
for model_name, config in MODELS.items():

    print(f"\n{'=' * 70}")
    print(f"Training: {model_name}")
    print(f"{'=' * 70}")

    output_dir = config["output_dir"]
    checkpoint_path = config["checkpoint"]

    output_dir.mkdir(
        parents=True,
        exist_ok=True,
    )

    checkpoint_path.parent.mkdir(
        parents=True,
        exist_ok=True,
    )

    # Create pretrained baseline model
    model = build_baseline_model(
        model_name=model_name,
        num_classes=NUM_CLASSES,
    ).to(device)

    # Weighted cross-entropy
    criterion = create_criterion(
        Ytr,
        NUM_CLASSES,
        device,
    )

    # AdamW optimizer
    optimizer = create_optimizer(
        model.parameters()
    )

    # ReduceLROnPlateau scheduler
    scheduler = create_scheduler(
        optimizer
    )

    # Automatic mixed precision
    scaler, amp_ctx = create_amp()

    best_score = -1.0
    best_state = None
    best_epoch = -1
    best_val = None
    best_train = None

    pat = PATIENCE_RUN
    history = []

    # Training loop
    for ep in range(
        1,
        EPOCHS_RUN + 1,
    ):

        trM = epoch_baseline(
            model=model,
            X=Xtr,
            Y=Ytr,
            criterion=criterion,
            optimizer=optimizer,
            scaler=scaler,
            amp_ctx=amp_ctx,
            device=device,
            batch_size=BATCH_SIZE,
            train=True,
        )

        vaM = epoch_baseline(
            model=model,
            X=Xva,
            Y=Yva,
            criterion=criterion,
            optimizer=optimizer,
            scaler=scaler,
            amp_ctx=amp_ctx,
            device=device,
            batch_size=BATCH_SIZE,
            train=False,
        )

        current_lr = optimizer.param_groups[0]["lr"]

        history.append(
            {
                "epoch": ep,
                "lr": current_lr,
                "tr_loss": trM["loss"],
                "tr_acc": trM["acc"],
                "tr_prec": trM["prec"],
                "tr_rec": trM["rec"],
                "tr_f1": trM["f1"],
                "tr_auc": trM["auc"],
                "tr_mcc": trM["mcc"],
                "va_loss": vaM["loss"],
                "va_acc": vaM["acc"],
                "va_prec": vaM["prec"],
                "va_rec": vaM["rec"],
                "va_f1": vaM["f1"],
                "va_auc": vaM["auc"],
                "va_mcc": vaM["mcc"],
            }
        )

        print(
            f"[Ep {ep:02d}] LR={current_lr:.2e} | "
            f"TR L={trM['loss']:.3f} "
            f"A={trM['acc']:.3f} "
            f"F1={trM['f1']:.3f} "
            f"AUC={trM['auc']:.3f} | "
            f"VA L={vaM['loss']:.3f} "
            f"A={vaM['acc']:.3f} "
            f"F1={vaM['f1']:.3f} "
            f"AUC={vaM['auc']:.3f}"
        )

        scheduler.step(
            vaM[STOP_METRIC]
        )

        score = vaM[
            STOP_METRIC
        ]

        if score > best_score:

            best_score = score

            best_state = {
                k: v.detach().cpu()
                for k, v in model.state_dict().items()
            }

            best_epoch = ep
            best_val = vaM.copy()
            best_train = trM.copy()

            pat = PATIENCE_RUN

        else:

            pat -= 1

            if pat <= 0:
                print("Early stop.")
                break


    # Save and restore best checkpoint
    if best_state is not None:

        torch.save(
            best_state,
            checkpoint_path,
        )

        model.load_state_dict(
            best_state,
            strict=True,
        )


    # Save epoch-wise metrics
    log_df = pd.DataFrame(
        history
    )

    csv_path = (
        output_dir
        / "train_val_metrics.csv"
    )

    try:

        log_df.to_csv(
            csv_path,
            index=False,
        )

    except PermissionError:

        csv_path = output_dir / (
            "train_val_metrics_"
            + datetime.now().strftime("%Y%m%d_%H%M%S")
            + ".csv"
        )

        log_df.to_csv(
            csv_path,
            index=False,
        )


    # Report best checkpoint metrics
    print(
        f"\n=== Best {model_name} checkpoint "
        f"by val {STOP_METRIC.upper()} "
        f"at epoch {best_epoch} ==="
    )

    print("VAL:")
    print(
        f"  loss={best_val['loss']:.3f} | "
        f"acc={best_val['acc']:.3f} | "
        f"prec={best_val['prec']:.3f} | "
        f"rec={best_val['rec']:.3f} | "
        f"f1={best_val['f1']:.3f} | "
        f"auc={best_val['auc']:.3f} | "
        f"mcc={best_val['mcc']:.3f}"
    )

    print("TRAIN:")
    print(
        f"  loss={best_train['loss']:.3f} | "
        f"acc={best_train['acc']:.3f} | "
        f"prec={best_train['prec']:.3f} | "
        f"rec={best_train['rec']:.3f} | "
        f"f1={best_train['f1']:.3f} | "
        f"auc={best_train['auc']:.3f} | "
        f"mcc={best_train['mcc']:.3f}"
    )

    print(
        f"\nCheckpoint saved to: {checkpoint_path}"
    )

    print(
        f"History CSV saved to: {csv_path}"
    )